services:
  vue_client:
    build:
      context: ./vue_client
      target: 'develop-stage'
    ports:
      - '4200:4200'
    volumes:
      - ./vue_client:/app
    command: npm run serve
  api_server:
    build:
      context: ./api_server
      target: 'develop-stage'
    ports:
      - '3000:3000'
    command: npm run start:dev
    volumes:
      - ./api_server:/app
    environment:
      - MONGO_URL=mongodb://mongo_db:27017/natural-harbor-finder
    links:
      - mongo_db
    depends_on:
      - mongo_db
  mongo_db:
    image: mongo
    ports:
      - '27017:27017'
